// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwBj0NtY9SPg_Cm6NpdCDUR1cZNgYDAI',
    appId: '1:435282133857:web:df63f137fd40d6fb8cbb20',
    messagingSenderId: '435282133857',
    projectId: 'travel--agency',
    authDomain: 'travel--agency.firebaseapp.com',
    storageBucket: 'travel--agency.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG1xAnOyu5SfirTTdimDhBHPjx1Yy3tGw',
    appId: '1:435282133857:android:e00d489b57ac443b8cbb20',
    messagingSenderId: '435282133857',
    projectId: 'travel--agency',
    storageBucket: 'travel--agency.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_HU1BYFsS-dHcAxlsBpzHVRUpxpZaE2Y',
    appId: '1:435282133857:ios:fd5feab2e4a5aa548cbb20',
    messagingSenderId: '435282133857',
    projectId: 'travel--agency',
    storageBucket: 'travel--agency.appspot.com',
    iosBundleId: 'com.example.travelAgency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_HU1BYFsS-dHcAxlsBpzHVRUpxpZaE2Y',
    appId: '1:435282133857:ios:fd5feab2e4a5aa548cbb20',
    messagingSenderId: '435282133857',
    projectId: 'travel--agency',
    storageBucket: 'travel--agency.appspot.com',
    iosBundleId: 'com.example.travelAgency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEwBj0NtY9SPg_Cm6NpdCDUR1cZNgYDAI',
    appId: '1:435282133857:web:67b9e53d65a5ca1f8cbb20',
    messagingSenderId: '435282133857',
    projectId: 'travel--agency',
    authDomain: 'travel--agency.firebaseapp.com',
    storageBucket: 'travel--agency.appspot.com',
  );
}
